# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bd8c79b7160f1e8df42eca5624d1906fe47fd6344165d13da15e5264573ade3491441255fbaadde25282e87600ed5e22dabebc9e545a5a318682a3cb03650c3

test:
  secret_key_base: 4b983bef463daeb3a4be72e69e4f67c26d48174f17ec14702bca57067f3b0a120f1f4bb74b8b4a8a0fe4659e7de9021e42ee7c7793bc702700fc22bd823893ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
